'use strict';
const http = require('http');
const https = require('https');
const { spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const PORT = process.env.PORT || 8080;
const DATA_DIR = process.env.HERMES_HOME || '/data';
const SESSIONS_FILE = path.join(DATA_DIR, 'sessions.json');
const AUTO_SETUP_ON_DEPLOY = (process.env.HERMES_AUTO_SETUP_ON_DEPLOY || '1') !== '0';

// v0.15.0: explicit HERMES_INSECURE opt-in for 0.0.0.0 bind — no inference
const LISTEN_HOST = process.env.RAILWAY_ENVIRONMENT || process.env.RENDER || process.env.FLY_APP_NAME
  ? '0.0.0.0'
  : (process.env.HERMES_INSECURE === '1' ? '0.0.0.0' : '127.0.0.1');

// ── Self-Improve Policy ──────────────────────────────────────────
const SI_MODE        = (process.env.SELF_IMPROVE_MODE || 'off').toLowerCase();
const SI_ALLOWED_RAW = process.env.SELF_IMPROVE_ALLOWED_REPOS || '';
const SI_ALLOWED     = SI_ALLOWED_RAW.split(',').map(r => r.trim()).filter(Boolean);
const SI_BRANCH_PFX  = process.env.SELF_IMPROVE_BRANCH_PREFIX || 'autofix/';
const GITHUB_TOKEN   = process.env.GITHUB_TOKEN || '';
const SI_DISPATCH_SEC = process.env.SELF_IMPROVE_DISPATCH_SECRET || '';

// Valid modes: off (blocked), propose (create PR), autopr (alias for propose), on (direct push)
const SI_VALID_MODES = ['on', 'propose', 'autopr'];

function getSIPolicy() {
  const blockers = [];
  if (!SI_VALID_MODES.includes(SI_MODE)) blockers.push('SELF_IMPROVE_MODE');
  if (SI_ALLOWED.length === 0) blockers.push('SELF_IMPROVE_ALLOWED_REPOS');
  return {
    mode: SI_MODE,
    write_policy: blockers.length === 0 ? 'allowed' : 'blocked',
    policy_blockers: blockers,
    repos_configured: SI_ALLOWED.length > 0,
    repos: SI_ALLOWED,
    branch_prefix: SI_BRANCH_PFX,
    token_present: GITHUB_TOKEN.length > 0,
    dispatch_secret_required: SI_DISPATCH_SEC.length > 0
  };
}

// GitHub API helper
function githubRequest(method, apiPath, body, token) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const opts = {
      hostname: 'api.github.com',
      path: apiPath,
      method,
      headers: {
        'User-Agent': 'hermes-agent/0.15.0',
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        ...(data ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) } : {})
      }
    };
    const req = https.request(opts, (res) => {
      let buf = '';
      res.on('data', d => { buf += d; });
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(buf) }); }
        catch { resolve({ status: res.statusCode, body: buf }); }
      });
    });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

async function siPushFile({ repo, filePath, content, message, baseBranch }) {
  const branch = SI_BRANCH_PFX + 'patch-' + Date.now();
  const [owner, repoName] = repo.split('/');
  const base = baseBranch || 'main';

  // 1. Get base branch HEAD sha
  const refRes = await githubRequest('GET', `/repos/${owner}/${repoName}/git/ref/heads/${base}`, null, GITHUB_TOKEN);
  if (refRes.status !== 200) throw new Error(`Could not get ref for ${base}: ${refRes.status}`);
  const baseSha = refRes.body.object.sha;

  // 2. Create autofix branch
  await githubRequest('POST', `/repos/${owner}/${repoName}/git/refs`, {
    ref: `refs/heads/${branch}`,
    sha: baseSha
  }, GITHUB_TOKEN);

  // 3. Get existing file SHA if it exists
  let existingSha;
  const fileRes = await githubRequest('GET', `/repos/${owner}/${repoName}/contents/${filePath}?ref=${branch}`, null, GITHUB_TOKEN);
  if (fileRes.status === 200) existingSha = fileRes.body.sha;

  // 4. Push file
  const pushBody = {
    message: message || `self-improve: update ${filePath}`,
    content: Buffer.from(content).toString('base64'),
    branch
  };
  if (existingSha) pushBody.sha = existingSha;

  const pushRes = await githubRequest('PUT', `/repos/${owner}/${repoName}/contents/${filePath}`, pushBody, GITHUB_TOKEN);
  if (pushRes.status !== 200 && pushRes.status !== 201)
    throw new Error(`Push failed: ${pushRes.status} ${JSON.stringify(pushRes.body)}`);

  // 5. If propose/autopr mode — open a PR automatically
  let pr = null;
  if (SI_MODE === 'propose' || SI_MODE === 'autopr') {
    const prRes = await githubRequest('POST', `/repos/${owner}/${repoName}/pulls`, {
      title: message || `self-improve: update ${filePath}`,
      head: branch,
      base,
      body: `Auto-generated by hermes-agent self-improve (mode: ${SI_MODE})\n\nFile: \`${filePath}\``
    }, GITHUB_TOKEN);
    if (prRes.status === 201) pr = { number: prRes.body.number, url: prRes.body.html_url };
  }

  return { branch, repo, file: filePath, commit: pushRes.body.commit?.sha, pr };
}

// ── Persistent session store ─────────────────────────────────────
let sessions = new Map();

function loadSessions() {
  try {
    if (fs.existsSync(SESSIONS_FILE)) {
      const raw = JSON.parse(fs.readFileSync(SESSIONS_FILE, 'utf8'));
      sessions = new Map(Object.entries(raw));
      console.log(`[memory] Loaded ${sessions.size} sessions from disk`);
    }
  } catch (e) {
    console.error('[memory] Failed to load sessions:', e.message);
  }
}

function saveSessions() {
  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    const obj = {};
    for (const [k, v] of sessions) obj[k] = v;
    fs.writeFileSync(SESSIONS_FILE, JSON.stringify(obj), 'utf8');
  } catch (e) {
    console.error('[memory] Failed to save sessions:', e.message);
  }
}

loadSessions();

function runDeploySetupOnce() {
  if (!AUTO_SETUP_ON_DEPLOY) return;
  try {
    const child = spawn('hermes', ['setup', '--non-interactive', '--deploy'], {
      env: { ...process.env, HERMES_HOME: DATA_DIR, HOME: DATA_DIR, HERMES_QUIET: '1' },
      stdio: 'pipe'
    });
    child.stdout.on('data', (d) => process.stdout.write(`[setup] ${d}`));
    child.stderr.on('data', (d) => process.stderr.write(`[setup] ${d}`));
    child.on('close', (code) => {
      if (code === 0) console.log('[setup] Deployment bootstrap completed');
      else console.warn(`[setup] Deployment bootstrap exited with code ${code}`);
    });
  } catch (e) {
    console.warn('[setup] Failed to launch deployment bootstrap:', e.message);
  }
}

runDeploySetupOnce();

setInterval(() => {
  const cut = Date.now() - 7 * 24 * 3600000;
  for (const [k, v] of sessions) if (v.t < cut) sessions.delete(k);
  saveSessions();
}, 5 * 60 * 1000);

// ── Sliding context window ───────────────────────────────────────
function buildContextHistory(sessionHistory) {
  const KEEP_RECENT = 20;
  if (sessionHistory.length <= KEEP_RECENT) return sessionHistory;
  const older = sessionHistory.slice(0, sessionHistory.length - KEEP_RECENT);
  const recent = sessionHistory.slice(-KEEP_RECENT);
  const summaryLines = older.map(m => `${m.role}: ${m.content.slice(0, 150)}`).join('\n');
  return [
    { role: 'system', content: `[Earlier conversation summary]\n${summaryLines}\n[End summary — full recent messages follow]` },
    ...recent
  ];
}

// ── CORS helper ──────────────────────────────────────────────────
function cors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,DELETE,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type,Authorization,x-ic-url,x-session-id,x-session-name,x-model');
}

function redactUrl(s) {
  return s.replace(/https?:\/\/[^\s"']*/g, (u) => {
    try { return new URL(u).hostname; } catch { return '[url]'; }
  });
}

function jsonReply(content, model) {
  return JSON.stringify({
    id: 'chatcmpl-' + Date.now(),
    object: 'chat.completion',
    created: Math.floor(Date.now() / 1000),
    model: model || 'hermes-agent',
    choices: [{ index: 0, message: { role: 'assistant', content }, finish_reason: 'stop' }],
    usage: { prompt_tokens: 0, completion_tokens: content.length, total_tokens: content.length }
  });
}

const HERMES_MODELS = [
  'hermes-agent',
  'nous-hermes-2-mixtral-8x7b',
  'nous-hermes-2-solar-10.7b',
  'nous-hermes-2-yi-34b',
  'nous-hermes-3-llama-3.1-70b'
];

// ── Request handler ──────────────────────────────────────────────
const server = http.createServer((req, res) => {
  cors(res);
  if (req.method === 'OPTIONS') { res.writeHead(200); return res.end(); }

  const url = req.url.split('?')[0];

  // Health
  if (req.method === 'GET' && (url === '/' || url === '/health' || url === '/status')) {
    const sessionList = [];
    for (const [k, v] of sessions)
      sessionList.push({ id: k, name: v.name || k, messages: v.h.length, last: new Date(v.t).toISOString() });
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ status: 'ok', service: 'hermes-agent', version: '0.15.0', sessions: sessionList }));
  }

  // Models
  if (req.method === 'GET' && url === '/models') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ object: 'list', data: HERMES_MODELS.map(id => ({ id, object: 'model' })) }));
  }

  // ── Self-Improve: policy diagnostic ─────────────────────────────
  if (req.method === 'GET' && url === '/self-improve/policy') {
    const policy = getSIPolicy();
    // Check repo accessibility directly (not just /user)
    const repoToCheck = SI_ALLOWED[0];
    const repoPath = repoToCheck ? `/repos/${repoToCheck}` : '/user';
    githubRequest('GET', repoPath, null, GITHUB_TOKEN)
      .then(r => {
        policy.api_reachable = r.status === 200;
        policy.repo_accessible = repoToCheck ? r.status === 200 : null;
        policy.api_user = r.status === 200 && !repoToCheck ? r.body.login : undefined;
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(policy));
      })
      .catch(() => {
        policy.api_reachable = false;
        policy.repo_accessible = false;
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(policy));
      });
    return;
  }

  // ── Self-Improve: push file to autofix/* branch ──────────────────
  if (req.method === 'POST' && url === '/self-improve') {
    let body = '';
    req.on('data', d => { body += d; });
    req.on('end', async () => {
      const policy = getSIPolicy();
      if (policy.write_policy !== 'allowed') {
        res.writeHead(403, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Write policy blocked', blockers: policy.policy_blockers }));
      }
      if (!GITHUB_TOKEN) {
        res.writeHead(403, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'GITHUB_TOKEN not set' }));
      }

      let payload;
      try { payload = JSON.parse(body); }
      catch {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Invalid JSON' }));
      }

      const { file, content, message, repo, base_branch } = payload;
      if (!file || !content) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'file and content are required' }));
      }

      const targetRepo = repo || SI_ALLOWED[0];
      if (!SI_ALLOWED.includes(targetRepo)) {
        res.writeHead(403, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: `Repo ${targetRepo} not in SELF_IMPROVE_ALLOWED_REPOS` }));
      }

      try {
        const result = await siPushFile({
          repo: targetRepo,
          filePath: file,
          content,
          message,
          baseBranch: base_branch || 'main'
        });
        console.log(`[self-improve] mode=${SI_MODE} pushed ${file} to ${result.branch} on ${targetRepo}${result.pr ? ' PR#' + result.pr.number : ''}`);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, ...result }));
      } catch (e) {
        console.error('[self-improve] Push failed:', e.message);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
      }
    });
    return;
  }

  // Delete session
  if (req.method === 'DELETE' && url === '/session') {
    const sid = req.headers['x-session-id'];
    if (sid && sessions.has(sid)) { sessions.delete(sid); saveSessions(); }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ ok: true }));
  }

  // Chat completions
  if (req.method === 'POST' && (url === '/v1/chat/completions' || url === '/api/chat')) {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      let payload;
      try { payload = JSON.parse(body); }
      catch {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Invalid JSON' }));
      }

      const userMsgs = (payload.messages || []).filter(m => m.role === 'user');
      const last = userMsgs[userMsgs.length - 1];
      if (!last) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'No user message' }));
      }

      const prompt = typeof last.content === 'string'
        ? last.content
        : (last.content || []).map(c => c.text || '').join(' ');

      const sid = req.headers['x-session-id'] || 'default';
      const yolo = sid === 'yolo';
      const sessionName = req.headers['x-session-name'] || sid;
      const model = req.headers['x-model'] || payload.model || 'hermes-agent';

      let sess;
      if (yolo) {
        sess = { h: [], t: Date.now(), name: 'yolo' };
      } else {
        if (!sessions.has(sid)) {
          sessions.set(sid, { h: [], t: Date.now(), name: sessionName });
          console.log(`[memory] New session: ${sid} (${sessionName})`);
        }
        sess = sessions.get(sid);
        sess.t = Date.now();
        if (sessionName !== sid) sess.name = sessionName;
      }

      const contextHistory = buildContextHistory(sess.h);
      console.log(`[memory] Session ${sid}: ${sess.h.length} stored, ${contextHistory.length} in context`);

      const histFile = path.join(os.tmpdir(), 'hist_' + Date.now() + '.json');
      const outFile  = path.join(os.tmpdir(), 'out_'  + Date.now() + '_' + Math.random().toString(36).slice(2) + '.txt');

      try { fs.writeFileSync(histFile, JSON.stringify(contextHistory)); } catch (e) {
        console.error('[memory] Failed to write hist file:', e.message);
      }

      const runner = process.env.HERMES_RUNNER || '/data/.hermes/hermes-agent/hermes_runner.py';
      const cwd    = process.env.HERMES_DIR    || '/data/.hermes/hermes-agent';

      const child = spawn('python3', [runner, outFile, prompt, '--history', histFile], {
        cwd, shell: false,
        env: { ...process.env, HERMES_QUIET: '1', HOME: '/data', PYTHONUNBUFFERED: '1' }
      });

      res.writeHead(200, { 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked' });

      let stderr = '';
      child.stderr.on('data', d => { stderr += d; });
      const ka = setInterval(() => { try { res.write(''); } catch {} }, 10000);

      const timer = setTimeout(() => {
        clearInterval(ka);
        child.kill('SIGTERM');
        setTimeout(() => { try { child.kill('SIGKILL'); } catch {} }, 2000);
        if (res.writableEnded) return;
        let text = 'Timed out after 5 minutes.';
        try { if (fs.existsSync(outFile)) text = fs.readFileSync(outFile, 'utf8').trim() || text; } catch {}
        try { fs.unlinkSync(outFile); } catch {}
        try { fs.unlinkSync(histFile); } catch {}
        res.end(jsonReply(text, model));
      }, 300000);

      child.on('close', () => {
        clearTimeout(timer);
        clearInterval(ka);
        if (res.writableEnded) return;

        let text = '';
        try { if (fs.existsSync(outFile)) text = fs.readFileSync(outFile, 'utf8').trim(); } catch {}
        try { fs.unlinkSync(outFile); } catch {}
        try { fs.unlinkSync(histFile); } catch {}

        if (!text) {
          text = stderr ? 'Error: ' + stderr.slice(0, 600) : '(no response)';
          if (stderr) console.error('[hermes] stderr:', redactUrl(stderr.slice(0, 400)));
        }

        if (!yolo) {
          sess.h.push({ role: 'user',      content: prompt });
          sess.h.push({ role: 'assistant', content: text });
          if (sess.h.length > 100) sess.h = sess.h.slice(-100);
          saveSessions();
          console.log(`[memory] Session ${sid} now has ${sess.h.length} messages`);
        }

        res.end(jsonReply(text, model));
      });
    });
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.timeout = 360000;
server.listen(PORT, LISTEN_HOST, () => {
  const policy = getSIPolicy();
  console.log(`Hermes gateway v0.15.0 on ${LISTEN_HOST}:${PORT}`);
  console.log(`Sessions file: ${SESSIONS_FILE}`);
  console.log(`Self-improve: mode=${SI_MODE} | policy=${policy.write_policy} | repos=${SI_ALLOWED.join(',') || 'none'}`);
  console.log(`Insecure bind: ${process.env.HERMES_INSECURE === '1' ? 'YES' : 'no'}`);
});
